<HCDPLayout>:
	rows: 1
	columns: 2
	padding:30
	spacing:20
	
	StackLayout:
		size_hint_x:.3
		orientation: 'tb-lr'
		spacing:10
		padding: 10
		canvas:
			Color:
				rgba: 83/255,81/255,86/255,1
			RoundedRectangle:
				pos: self.pos
				size: self.size
		Button: 
			text: "Configurar Medidor"
			size_hint_y:.1
			on_release: root.abrirConfigMedidor()
		Button:
			text: "Configurar Servidor"
			size_hint_y:.1
			on_release: root.abrirConfigServidor()
